<#
合成原生界面回归：不加载设备配置和凭据，不访问 NAS。
输出来自测试宿主自身的 XAML 渲染，不截取桌面或其他应用。
#>
param([switch]$SkipBuild, [switch]$ContinueOnFailure, [string[]]$Scenarios, [string[]]$States, [int]$WindowWidth = 1280, [int]$WindowHeight = 820,
    [ValidateSet('auto', 'open', 'compact', 'cycle')][string]$PaneState = 'auto',
    [ValidateSet('', 'en-US', 'zh-CN')][string]$Language = '')
$ErrorActionPreference = 'Stop'
$windowsRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'))
$output = Join-Path $windowsRoot 'dist\ui-smoke-x64'
$review = Join-Path $windowsRoot ('dist\ui-review-' + (Get-Date -Format 'yyyyMMdd-HHmmss'))
if (-not $SkipBuild) {
    & dotnet publish (Join-Path $windowsRoot 'src\LanStash.App\LanStash.App.csproj') `
        -c Release -p:Platform=x64 -r win-x64 --self-contained true `
        -p:LanStashStandalone=true -p:LanStashUiSmoke=true -o $output
    if ($LASTEXITCODE -ne 0) { throw '合成 UI 宿主构建失败。' }
}
New-Item -ItemType Directory -Path $review | Out-Null
$cases = @(
    @('vm-image-import', 'Light', 'vmimport-form'), @('vm-image-import', 'Dark', 'vmimport-form'),
    @('vm-image-import', 'Light', 'vmimport-run'), @('vm-image-import', 'Light', 'vmimport-review'),
    @('vm-image-import', 'Light', 'vmimport-unknown'), @('vm-image-import', 'Light', 'vmimport-readonly'),
    @('vm-image-import', 'Light', 'vmimport-empty'), @('vm-image-import', 'Light', 'vmimport-error'),
    @('vm-image-import', 'Light', 'vmimport-loading'), @('vm-image-import', 'Light', 'vmimport-edit'),
    @('vm-image-import', 'Light', 'vmimport-close-busy'), @('vm-image-import', 'Light', 'vmimport-auth'),
    @('vm-image-import', 'Light', 'vmimport-recovery'),
    @('vm-networks', 'Light', 'network-form'), @('vm-networks', 'Dark', 'network-form'),
    @('vm-networks', 'Light', 'network-rename-form'), @('vm-networks', 'Light', 'network-rename-run'),
    @('vm-networks', 'Light', 'network-delete-run'), @('vm-networks', 'Light', 'network-large'),
    @('vm-networks', 'Light', 'network-unknown'), @('vm-networks', 'Light', 'network-review'),
    @('vm-networks', 'Light', 'network-tail-change'), @('vm-networks', 'Light', 'network-selection-change'),
    @('vm-networks', 'Light', 'network-close-busy'), @('vm-networks', 'Light', 'network-auth'),
    @('vm-networks', 'Light', 'network-empty'), @('vm-networks', 'Light', 'network-error'),
    @('vm-networks', 'Light', 'network-frozen'), @('vm-networks', 'Light', 'network-readonly'),
    @('vm-networks', 'Light', 'network-loading'), @('vm-networks', 'Light', 'network-rename-invalid'),
    @('vm-networks', 'Light', 'network-rename-duplicate'),
    @('notification-lifecycle', 'Light', 'notification-open'), @('notification-lifecycle', 'Dark', 'notification-open'),
    @('notification-lifecycle', 'Light', 'notification-invalid'), @('notification-lifecycle', 'Light', 'notification-old-context'),
    @('notification-lifecycle', 'Light', 'notification-dispose'), @('notification-lifecycle', 'Light', 'notification-generation'),
    @('notification-lifecycle', 'Light', 'notification-replaced'), @('notification-lifecycle', 'Light', 'notification-exit'),
    @('cloud-settings', 'Light', 'cloud-empty'), @('cloud-settings', 'Dark', 'cloud-empty'),
    @('cloud-settings', 'Light', 'cloud-writeback-form'), @('cloud-settings', 'Dark', 'cloud-writeback-form'),
    @('cloud-settings', 'Light', 'cloud-writeback-enable'), @('cloud-settings', 'Light', 'cloud-writeback-all-shares'),
    @('cloud-settings', 'Light', 'cloud-writeback-invalid-scope'),
    @('cloud-settings', 'Light', 'cloud-writeback-pending'), @('cloud-settings', 'Dark', 'cloud-writeback-pending'),
    @('cloud-settings', 'Light', 'cloud-writeback-directory'), @('cloud-settings', 'Dark', 'cloud-writeback-directory'),
    @('cloud-settings', 'Light', 'cloud-writeback-move-unknown'), @('cloud-settings', 'Dark', 'cloud-writeback-move-unknown'),
    @('cloud-settings', 'Light', 'cloud-writeback-move-next'), @('cloud-settings', 'Light', 'cloud-writeback-move-local'),
    @('cloud-settings', 'Light', 'cloud-writeback-move-rejected'),
    @('cloud-settings', 'Light', 'cloud-writeback-delete-enable'),
    @('cloud-settings', 'Light', 'cloud-writeback-delete-prepared'), @('cloud-settings', 'Dark', 'cloud-writeback-delete-prepared'),
    @('cloud-settings', 'Light', 'cloud-writeback-delete-unknown'), @('cloud-settings', 'Light', 'cloud-writeback-delete-local'),
    @('cloud-settings', 'Light', 'cloud-writeback-released'), @('cloud-settings', 'Dark', 'cloud-writeback-released'),
    @('cloud-settings', 'Light', 'cloud-writeback-review'), @('cloud-settings', 'Light', 'cloud-writeback-retry'),
    @('cloud-settings', 'Light', 'cloud-writeback-export'), @('cloud-settings', 'Light', 'cloud-writeback-error'),
    @('cloud-settings', 'Light', 'cloud-writeback-close-busy'),
    @('cloud-settings', 'Light', 'cloud-confirm'), @('cloud-settings', 'Dark', 'cloud-confirm'),
    @('cloud-settings', 'Light', 'cloud-enable'), @('cloud-settings', 'Light', 'cloud-cancel'),
    @('cloud-settings', 'Light', 'cloud-back'), @('cloud-settings', 'Light', 'cloud-leave-confirm'),
    @('cloud-settings', 'Light', 'cloud-stale-confirm'),
    @('cloud-settings', 'Light', 'cloud-refresh-form'), @('cloud-settings', 'Dark', 'cloud-refresh-form'),
    @('cloud-settings', 'Light', 'cloud-refresh-done'), @('cloud-settings', 'Dark', 'cloud-refresh-partial'),
    @('cloud-settings', 'Light', 'cloud-refresh-empty'), @('cloud-settings', 'Light', 'cloud-refresh-error'),
    @('cloud-settings', 'Light', 'cloud-refresh-cancel'), @('cloud-settings', 'Light', 'cloud-refresh-leave'),
    @('cloud-settings', 'Light', 'cloud-refresh-duplicate'),
    @('cloud-settings', 'Light', 'cloud-refresh-disconnected'),
    @('cloud-settings', 'Light', 'cloud-refresh-removed'), @('cloud-settings', 'Dark', 'cloud-refresh-retained'),
    @('tray-lifecycle', 'Light', 'tray-recover'), @('tray-lifecycle', 'Dark', 'tray-locale'),
    @('tray-lifecycle', 'Light', 'tray-keys'), @('tray-lifecycle', 'Light', 'tray-messages'),
    @('tray-lifecycle', 'Light', 'tray-unavailable'), @('tray-lifecycle', 'Light', 'tray-dispose'),
    @('tray-lifecycle', 'Light', 'tray-close-fallback'),
    @('files-folder-upload', 'Light', 'folder-form'), @('files-folder-upload', 'Dark', 'folder-form'),
    @('files-folder-upload', 'Light', 'folder-run'), @('files-folder-upload', 'Dark', 'folder-run'),
    @('files-folder-upload', 'Light', 'folder-unknown'), @('files-folder-upload', 'Light', 'folder-file-cancel'),
    @('files-folder-upload', 'Light', 'folder-dialog-cancel'), @('files-folder-upload', 'Light', 'folder-picker-cancel'),
    @('files-folder-upload', 'Light', 'folder-prep-cancel'), @('files-folder-upload', 'Light', 'folder-close'),
    @('files-folder-upload', 'Light', 'folder-source-changed'), @('files-folder-upload', 'Light', 'folder-target-changed'),
    @('vm-console', 'Light', 'vmconsole-ready'), @('vm-console', 'Dark', 'vmconsole-ready'),
    @('vm-console', 'Light', 'vmconsole-policy'), @('vm-console', 'Dark', 'vmconsole-policy'),
    @('vm-console', 'Light', 'vmconsole-navigate'), @('vm-console', 'Light', 'vmconsole-reopen'),
    @('vm-console', 'Light', 'vmconsole-fullscreen'), @('vm-console', 'Light', 'vmconsole-loading'),
    @('vm-console', 'Light', 'vmconsole-error'), @('vm-console', 'Light', 'vmconsole-close-document'),
    @('vm-console', 'Light', 'vmconsole-unavailable'), @('vm-console', 'Light', 'vmconsole-stopped'),
    @('vm-console', 'Light', 'vmconsole-managed'), @('vm-console', 'Dark', 'vmconsole-managed'),
    @('vm-console', 'Light', 'vmconsole-managed-close'),
    @('vm-console', 'Light', 'vmconsole-managed-reconnect'),
    @('vm-console', 'Light', 'vmconsole-managed-alias'), @('vm-console', 'Dark', 'vmconsole-managed-alias'),
    @('vm-console', 'Light', 'vmconsole-managed-ip'), @('vm-console', 'Light', 'vmconsole-managed-ipv6'),
    @('vm-console', 'Light', 'vmconsole-managed-locale-error'), @('vm-console', 'Light', 'vmconsole-managed-close-locale'),
    @('vm-image-delete', 'Light', 'vmimage-form'), @('vm-image-delete', 'Light', 'vmimage-run'),
    @('vm-image-delete', 'Light', 'vmimage-unknown'), @('vm-image-delete', 'Light', 'vmimage-rejected'), @('vm-image-delete', 'Light', 'vmimage-auth'),
    @('vm-image-delete', 'Light', 'vmimage-cancel'), @('vm-image-delete', 'Light', 'vmimage-tail-change'),
    @('vm-image-delete', 'Light', 'vmimage-selection-change'), @('vm-image-delete', 'Light', 'vmimage-readonly'),
    @('vm-image-delete', 'Light', 'vmimage-review'), @('vm-image-delete', 'Light', 'vmimage-review-after'),
    @('vm-image-delete', 'Light', 'vmimage-empty'), @('vm-image-delete', 'Light', 'vmimage-running'), @('vm-image-delete', 'Light', 'vmimage-close-busy'),
    @('vm-image-delete', 'Dark', 'vmimage-form'), @('vm-image-delete', 'Dark', 'vmimage-unknown'),
    @('vm-task-cleanup', 'Light', 'taskclear-form'), @('vm-task-cleanup', 'Light', 'taskclear-success'),
    @('vm-task-cleanup', 'Light', 'taskclear-large'), @('vm-task-cleanup', 'Light', 'taskclear-added'),
    @('vm-task-cleanup', 'Light', 'taskclear-changed'), @('vm-task-cleanup', 'Light', 'taskclear-unknown'),
    @('vm-task-cleanup', 'Light', 'taskclear-review'), @('vm-task-cleanup', 'Light', 'taskclear-close'),
    @('vm-task-cleanup', 'Light', 'taskclear-readonly'), @('vm-task-cleanup', 'Light', 'taskclear-protected'),
    @('vm-task-cleanup', 'Dark', 'taskclear-form'), @('vm-task-cleanup', 'Dark', 'taskclear-unknown'),
    @('vm-delete', 'Light', 'vmdelete-form'), @('vm-delete', 'Light', 'vmdelete-run'),
    @('vm-delete', 'Light', 'vmdelete-unknown'), @('vm-delete', 'Light', 'vmdelete-rejected'), @('vm-delete', 'Light', 'vmdelete-auth'),
    @('vm-delete', 'Light', 'vmdelete-cancel'), @('vm-delete', 'Light', 'vmdelete-tail-change'),
    @('vm-delete', 'Light', 'vmdelete-selection-change'), @('vm-delete', 'Light', 'vmdelete-readonly'),
    @('vm-delete', 'Light', 'vmdelete-review'), @('vm-delete', 'Light', 'vmdelete-review-after'),
    @('vm-delete', 'Light', 'vmdelete-empty'), @('vm-delete', 'Light', 'vmdelete-running'), @('vm-delete', 'Light', 'vmdelete-close-busy'),
    @('vm-delete', 'Dark', 'vmdelete-form'), @('vm-delete', 'Dark', 'vmdelete-unknown'),
    @('vm-power-batch', 'Light', 'vmbatch-form'), @('vm-power-batch', 'Light', 'vmbatch-on'),
    @('vm-power-batch', 'Light', 'vmbatch-shutdown'), @('vm-power-batch', 'Light', 'vmbatch-off-form'), @('vm-power-batch', 'Light', 'vmbatch-off'),
    @('vm-power-batch', 'Light', 'vmbatch-unknown'), @('vm-power-batch', 'Light', 'vmbatch-auth'),
    @('vm-power-batch', 'Light', 'vmbatch-cancel'), @('vm-power-batch', 'Light', 'vmbatch-tail-change'),
    @('vm-power-batch', 'Light', 'vmbatch-selection-change'), @('vm-power-batch', 'Light', 'vmbatch-readonly'),
    @('vm-power-batch', 'Light', 'vmbatch-review'), @('vm-power-batch', 'Light', 'vmbatch-review-after'),
    @('vm-power-batch', 'Light', 'vmbatch-empty'), @('vm-power-batch', 'Light', 'vmbatch-close-busy'),
    @('vm-power-batch', 'Dark', 'vmbatch-off-form'), @('vm-power-batch', 'Dark', 'vmbatch-unknown'),
    @('files-recycle-recovery', 'Light', 'recycle-review-form'), @('files-recycle-recovery', 'Light', 'recycle-review-empty'),
    @('files-recycle-recovery', 'Light', 'recycle-review-success'), @('files-recycle-recovery', 'Light', 'recycle-review-pending'),
    @('files-recycle-recovery', 'Light', 'recycle-review-auth'), @('files-recycle-recovery', 'Light', 'recycle-review-load-error'),
    @('files-recycle-recovery', 'Light', 'recycle-review-close-busy'), @('files-recycle-recovery', 'Light', 'recycle-review-reopen'),
    @('files-recycle-recovery', 'Dark', 'recycle-review-form'), @('files-recycle-recovery', 'Dark', 'recycle-review-success'),
    @('files-recycle-recovery', 'Light', 'restore-review-success'), @('files-recycle-recovery', 'Light', 'restore-review-pending'),
    @('files-recycle-recovery', 'Light', 'restore-review-reopen'), @('files-recycle-recovery', 'Dark', 'restore-review-form'),
    @('files-copy-recovery', 'Light', 'review-form'), @('files-copy-recovery', 'Light', 'review-empty'),
    @('files-copy-recovery', 'Light', 'review-success'), @('files-copy-recovery', 'Light', 'review-pending'),
    @('files-copy-recovery', 'Light', 'review-auth'), @('files-copy-recovery', 'Light', 'review-load-error'),
    @('files-copy-recovery', 'Light', 'review-close-busy'), @('files-copy-recovery', 'Light', 'review-reopen'),
    @('files-copy-recovery', 'Dark', 'review-form'), @('files-copy-recovery', 'Dark', 'review-success'),
    @('files-copy-conflicts', 'Light', 'conflict-copy-skip'), @('files-copy-conflicts', 'Light', 'conflict-move-skip'),
    @('files-copy-conflicts', 'Light', 'conflict-copy-all-skip'), @('files-copy-conflicts', 'Light', 'conflict-copy-single-skip'),
    @('files-copy-conflicts', 'Light', 'conflict-copy-overwrite-form'), @('files-copy-conflicts', 'Light', 'conflict-copy-overwrite'),
    @('files-copy-conflicts', 'Light', 'conflict-move-overwrite'), @('files-copy-conflicts', 'Light', 'conflict-copy-single-overwrite'),
    @('files-copy-conflicts', 'Light', 'conflict-copy-overwrite-toggle-back'), @('files-copy-conflicts', 'Light', 'conflict-copy-overwrite-unknown'),
    @('files-copy-conflicts', 'Light', 'conflict-move-overwrite-cancel'),
    @('files-copy-conflicts', 'Dark', 'conflict-copy-overwrite-form'), @('files-copy-conflicts', 'Dark', 'conflict-copy-all-skip'),
    @('files-large-recycle', 'Light', 'recycle-form'), @('files-large-recycle', 'Light', 'restore-grid'),
    @('files-large-recycle', 'Light', 'recycle-run'), @('files-large-recycle', 'Light', 'restore-run'),
    @('files-large-recycle', 'Light', 'recycle-unknown'), @('files-large-recycle', 'Light', 'restore-unknown'),
    @('files-large-recycle', 'Light', 'recycle-cancel'), @('files-large-recycle', 'Light', 'restore-cancel'),
    @('files-large-recycle', 'Light', 'recycle-change-tail'), @('files-large-recycle', 'Light', 'restore-metadata'),
    @('files-large-recycle', 'Light', 'restore-auth'), @('files-large-recycle', 'Light', 'restore-throw-auth'),
    @('files-large-recycle', 'Dark', 'recycle-form'), @('files-large-recycle', 'Dark', 'restore-unknown'),
    @('files-large-copy-move', 'Light', 'copy-large-form'), @('files-large-copy-move', 'Light', 'copy-large-grid'),
    @('files-large-copy-move', 'Light', 'copy-large-run'), @('files-large-copy-move', 'Light', 'move-large-run'),
    @('files-large-copy-move', 'Light', 'copy-large-unknown'), @('files-large-copy-move', 'Light', 'move-large-unknown'),
    @('files-large-copy-move', 'Light', 'copy-large-cancel'), @('files-large-copy-move', 'Light', 'copy-large-change-tail'),
    @('files-large-copy-move', 'Light', 'copy-large-metadata'), @('files-large-copy-move', 'Light', 'copy-large-auth'),
    @('files-large-copy-move', 'Light', 'copy-large-readonly'),
    @('files-large-copy-move', 'Dark', 'copy-large-run'), @('files-large-copy-move', 'Dark', 'copy-large-unknown'),
    @('files-upload-batch', 'Light', 'upload-large'), @('files-upload-batch', 'Light', 'upload-drop'),
    @('files-upload-batch', 'Light', 'upload-unknown'), @('files-upload-batch', 'Light', 'upload-cancel'),
    @('files-upload-batch', 'Light', 'upload-target-changed'), @('files-upload-batch', 'Light', 'upload-overwrite-changed'),
    @('files-upload-batch', 'Light', 'upload-close-picker'), @('files-upload-batch', 'Light', 'upload-picker-cancel'),
    @('files-upload-batch', 'Light', 'upload-duplicate'), @('files-upload-batch', 'Light', 'upload-overwrite'),
    @('files-upload-batch', 'Dark', 'upload-large'), @('files-upload-batch', 'Dark', 'upload-unknown'),
    @('files-selection-download', 'Light', 'selection-list'), @('files-selection-download', 'Light', 'selection-grid'),
    @('files-selection-download', 'Light', 'selection-download'), @('files-selection-download', 'Light', 'selection-single-file'),
    @('files-selection-download', 'Light', 'selection-single-folder'), @('files-selection-download', 'Light', 'selection-cancel'),
    @('files-selection-download', 'Light', 'selection-invalid'), @('files-selection-download', 'Light', 'selection-changed'),
    @('files-selection-download', 'Light', 'selection-close-picker'), @('files-selection-download', 'Light', 'selection-picker-cancel'),
    @('files-selection-download', 'Dark', 'selection-download'), @('files-selection-download', 'Dark', 'selection-grid'),
    @('remote-mounts', 'Light', 'mount-loading'), @('remote-mounts', 'Light', 'mount-error'),
    @('remote-mounts', 'Light', 'mount-empty'), @('remote-mounts', 'Light', 'mount-filter'),
    @('remote-mounts', 'Light', 'mount-create'), @('remote-mounts', 'Light', 'mount-confirm'),
    @('remote-mounts', 'Light', 'mount-change'), @('remote-mounts', 'Light', 'mount-nfs'),
    @('remote-mounts', 'Light', 'mount-same'), @('remote-mounts', 'Light', 'mount-move'),
    @('remote-mounts', 'Light', 'mount-disconnect'), @('remote-mounts', 'Light', 'mount-unknown'),
    @('remote-mounts', 'Light', 'mount-review'), @('remote-mounts', 'Light', 'mount-reopen'),
    @('remote-mounts', 'Light', 'mount-close-busy'), @('remote-mounts', 'Light', 'mount-profile-change'),
    @('remote-mounts', 'Dark', 'mount-confirm'), @('remote-mounts', 'Dark', 'mount-unknown'), @('remote-mounts', 'Dark', 'mount-reopen'),
    @('files-favorites', 'Light', 'favorite-add'),
    @('files-favorites', 'Light', 'favorite-remove'),
    @('files-favorites', 'Light', 'favorite-unknown'),
    @('files-favorites', 'Light', 'favorite-review'),
    @('files-favorites', 'Light', 'favorite-permission'),
    @('files-favorites', 'Light', 'favorite-readonly'),
    @('files-favorites', 'Light', 'favorite-close-busy'),
    @('files-favorites', 'Light', 'favorite-current-folder'),
    @('files-favorites', 'Light', 'favorite-profile-change'),
    @('files-favorites', 'Dark', 'favorite-add'),
    @('files-favorites', 'Dark', 'favorite-remove'),
    @('files-favorites', 'Dark', 'favorite-unknown'),
    @('container-image-pull', 'Light', 'pull-confirm'),
    @('container-image-pull', 'Light', 'pull-running'),
    @('container-image-pull', 'Light', 'pull-ready'),
    @('container-image-pull', 'Light', 'pull-no-receipt'),
    @('container-image-pull', 'Light', 'pull-review'),
    @('container-image-pull', 'Light', 'pull-rejected'),
    @('container-image-pull', 'Light', 'pull-reopen'),
    @('container-image-pull', 'Light', 'pull-recovery'),
    @('container-image-pull', 'Light', 'pull-close-busy'),
    @('container-image-pull', 'Light', 'pull-change'),
    @('container-image-pull', 'Light', 'pull-auto'),
    @('container-image-pull', 'Light', 'pull-read-error'),
    @('container-image-pull', 'Light', 'pull-readonly'),
    @('container-image-pull', 'Dark', 'pull-confirm'),
    @('container-image-pull', 'Dark', 'pull-running'),
    @('container-image-pull', 'Dark', 'pull-no-receipt'),
    @('container-image-delete', 'Light', 'image-delete-readonly'),
    @('container-image-delete', 'Light', 'image-delete-loading'),
    @('container-image-delete', 'Light', 'image-delete-error'),
    @('container-image-delete', 'Light', 'image-delete-empty'),
    @('container-image-delete', 'Light', 'image-delete-confirm'),
    @('container-image-delete', 'Light', 'image-delete-change'),
    @('container-image-delete', 'Light', 'image-delete-success'),
    @('container-image-delete', 'Light', 'image-delete-partial'),
    @('container-image-delete', 'Light', 'image-delete-unknown'),
    @('container-image-delete', 'Light', 'image-delete-rejected'),
    @('container-image-delete', 'Light', 'image-delete-pending'),
    @('container-image-delete', 'Light', 'image-delete-recovered'),
    @('container-image-delete', 'Light', 'image-delete-close-busy'),
    @('container-image-delete', 'Dark', 'image-delete-confirm'),
    @('container-image-delete', 'Dark', 'image-delete-partial'),
    @('container-image-delete', 'Dark', 'image-delete-unknown'),
    @('container-operations', 'Light', 'ops-transition-state'), @('container-operations', 'Dark', 'ops-transition-state'),
    @('container-operations', 'Light', 'ops-transition-stop'), @('container-operations', 'Dark', 'ops-transition-stop'),
    @('container-operations', 'Light', 'ops-transition-restart'),
    @('container-operations', 'Light', 'ops-confirm'), @('container-operations', 'Dark', 'ops-confirm'),
    @('container-operations', 'Light', 'ops-start'), @('container-operations', 'Dark', 'ops-start'),
    @('container-operations', 'Light', 'ops-stop'), @('container-operations', 'Light', 'ops-restart'),
    @('container-operations', 'Light', 'ops-delete'), @('container-operations', 'Dark', 'ops-delete'),
    @('container-operations', 'Light', 'ops-empty'), @('container-operations', 'Light', 'ops-filtered'),
    @('container-operations', 'Light', 'ops-error'), @('container-operations', 'Light', 'ops-loading'),
    @('container-operations', 'Light', 'ops-readonly'), @('container-operations', 'Light', 'ops-change'),
    @('container-operations', 'Light', 'ops-unknown'), @('container-operations', 'Light', 'ops-recovery'),
    @('container-operations', 'Light', 'ops-recovered'), @('container-operations', 'Light', 'ops-reopen'),
    @('container-operations', 'Light', 'ops-permission'), @('container-operations', 'Light', 'ops-close-busy'),
    @('files-extract', 'Light', 'extract-form'), @('files-extract', 'Dark', 'extract-form'),
    @('files-extract', 'Light', 'extract-password'), @('files-extract', 'Dark', 'extract-password'),
    @('files-extract', 'Light', 'extract-retry'), @('files-extract', 'Light', 'extract-success'),
    @('files-extract', 'Light', 'extract-unknown'), @('files-extract', 'Light', 'extract-working'),
    @('files-extract', 'Light', 'extract-confirm'), @('files-extract', 'Dark', 'extract-confirm'),
    @('files-extract', 'Light', 'extract-confirm-reset'), @('files-extract', 'Light', 'extract-overwrite'),
    @('files-extract', 'Light', 'extract-flatten'),
    @('files-archive', 'Light', 'archive-form'), @('files-archive', 'Dark', 'archive-form'),
    @('files-archive', 'Light', 'archive-large-list'), @('files-archive', 'Dark', 'archive-large-list'),
    @('files-archive', 'Light', 'archive-large-grid'), @('files-archive', 'Dark', 'archive-large-grid'),
    @('files-archive', 'Light', 'archive-large-success-list'), @('files-archive', 'Dark', 'archive-large-success-list'),
    @('files-archive', 'Light', 'archive-large-success-grid'), @('files-archive', 'Dark', 'archive-large-success-grid'),
    @('files-archive', 'Light', 'archive-large-changed'), @('files-archive', 'Dark', 'archive-large-changed'),
    @('files-archive', 'Light', 'archive-success'), @('files-archive', 'Dark', 'archive-success'),
    @('files-archive', 'Light', 'archive-invalid'), @('files-archive', 'Light', 'archive-error'),
    @('files-archive', 'Light', 'archive-unknown'), @('files-archive', 'Light', 'archive-working'),
    @('vm-create', 'Light', 'vmcreate-readonly'), @('vm-create', 'Light', 'vmcreate-loading'),
    @('vm-create', 'Light', 'vmcreate-empty'), @('vm-create', 'Light', 'vmcreate-error'),
    @('vm-create', 'Light', 'vmcreate-form'), @('vm-create', 'Dark', 'vmcreate-form'),
    @('vm-create', 'Light', 'vmcreate-confirm'),
    @('vm-create', 'Light', 'vmcreate-invalid'), @('vm-create', 'Light', 'vmcreate-success'),
    @('vm-create', 'Dark', 'vmcreate-success'), @('vm-create', 'Light', 'vmcreate-wait'),
    @('vm-create', 'Light', 'vmcreate-recovery'), @('vm-create', 'Light', 'vmcreate-unknown'),
    @('vm-create', 'Light', 'vmcreate-image'), @('vm-create', 'Light', 'vmcreate-partial'),
    @('vm-create', 'Light', 'vmcreate-close-busy'),
    @('vm-create', 'Light', 'vmcreate-power-confirm'), @('vm-create', 'Dark', 'vmcreate-power-confirm'),
    @('vm-create', 'Light', 'vmcreate-power-success'), @('vm-create', 'Light', 'vmcreate-power-wait'),
    @('vm-create', 'Dark', 'vmcreate-power-unknown'), @('vm-create', 'Light', 'vmcreate-power-readonly'),
    @('vm-create', 'Light', 'vmcreate-advanced-form'), @('vm-create', 'Dark', 'vmcreate-advanced-form'),
    @('vm-create', 'Light', 'vmcreate-advanced-success'), @('vm-create', 'Dark', 'vmcreate-advanced-success'),
    @('vm-create', 'Light', 'vmcreate-advanced-edit'), @('vm-create', 'Light', 'vmcreate-advanced-invalid'),
    @('vm-create', 'Light', 'vmcreate-advanced-error'), @('vm-create', 'Light', 'vmcreate-advanced-frozen'),
    @('vm-create', 'Light', 'vmcreate-advanced-unknown'), @('vm-create', 'Light', 'vmcreate-advanced-close-busy'),
    @('vm-create', 'Light', 'vmcreate-advanced-fallback'),
    @('vm-create', 'Light', 'vmcreate-advanced-confirm'), @('vm-create', 'Dark', 'vmcreate-advanced-confirm'),
    @('vm-create', 'Light', 'vmcreate-advanced-ui-submit'),
    @('vm-create', 'Light', 'vmcreate-image-power'), @('vm-create', 'Light', 'vmcreate-image-wait'),
    @('vm-create', 'Light', 'vmcreate-image-unknown'), @('vm-create', 'Light', 'vmcreate-image-hardware'),
    @('vm-tasks', 'Light', 'vmtasks-unavailable'), @('vm-tasks', 'Light', 'vmtasks-empty'),
    @('vm-tasks', 'Light', 'vmtasks-loading'), @('vm-tasks', 'Light', 'vmtasks-error'),
    @('vm-tasks', 'Light', 'vmtasks-content'), @('vm-tasks', 'Dark', 'vmtasks-content'),
    @('vm-tasks', 'Light', 'vmtasks-refresh-error'), @('vm-tasks', 'Light', 'vmtasks-finished'),
    @('vm-tasks', 'Light', 'vmtasks-poll'), @('vm-tasks', 'Light', 'vmtasks-hide'),
    @('vm-settings', 'Light', 'vmsettings-readonly'), @('vm-settings', 'Light', 'vmsettings-loading'),
    @('vm-settings', 'Light', 'vmsettings-error'), @('vm-settings', 'Light', 'vmsettings-save'),
    @('vm-settings', 'Dark', 'vmsettings-save'), @('vm-settings', 'Light', 'vmsettings-running'),
    @('vm-settings', 'Light', 'vmsettings-invalid'), @('vm-settings', 'Light', 'vmsettings-partial'),
    @('vm-settings', 'Dark', 'vmsettings-partial'),
    @('vm-settings', 'Light', 'vmsettings-priority-form'), @('vm-settings', 'Dark', 'vmsettings-priority-form'),
    @('vm-settings', 'Light', 'vmsettings-priority-save'), @('vm-settings', 'Light', 'vmsettings-priority-running'),
    @('vm-settings', 'Light', 'vmsettings-priority-unknown'), @('vm-settings', 'Dark', 'vmsettings-priority-unknown'),
    @('vm-settings', 'Light', 'vmsettings-priority-readonly'), @('vm-settings', 'Light', 'vmsettings-priority-custom'),
    @('vm-power', 'Light', 'vmpower-readonly'), @('vm-power', 'Light', 'vmpower-loading'),
    @('vm-power', 'Light', 'vmpower-error'), @('vm-power', 'Light', 'vmpower-on'),
    @('vm-power', 'Light', 'vmpower-shutdown'), @('vm-power', 'Light', 'vmpower-off'),
    @('vm-power', 'Dark', 'vmpower-off'), @('vm-power', 'Light', 'vmpower-unknown'),
    @('vm-power', 'Dark', 'vmpower-unknown'), @('vm-power', 'Light', 'vmpower-rejected'),
    @('vm-power', 'Light', 'vmpower-pending'), @('vm-power', 'Light', 'vmpower-recovered'),
    @('vm-power', 'Light', 'vmpower-close-busy'),
    @('files-drag-move', 'Light', 'drag-confirm'), @('files-drag-move', 'Dark', 'drag-confirm'),
    @('files-drag-move', 'Light', 'drag-text'), @('files-drag-move', 'Light', 'drag-forged'),
    @('files-drag-move', 'Light', 'drag-stale'), @('files-drag-move', 'Light', 'drag-readonly'),
    @('files-drag-move', 'Light', 'drag-revoked'), @('files-drag-move', 'Light', 'drag-partial'),
    @('files-drag-move', 'Light', 'drag-undo'),
    @('transfer-pagination', 'Light', 'transfer-pages-initial'), @('transfer-pagination', 'Dark', 'transfer-pages-initial'),
    @('transfer-pagination', 'Light', 'transfer-pages-more'), @('transfer-pagination', 'Light', 'transfer-pages-all'),
    @('transfer-pagination', 'Light', 'transfer-pages-refresh'), @('transfer-pagination', 'Light', 'transfer-pages-error'),
    @('transfer-pagination', 'Dark', 'transfer-pages-error'), @('transfer-pagination', 'Light', 'transfer-pages-retry'),
    @('transfer-pagination', 'Light', 'transfer-pages-busy'), @('transfer-pagination', 'Dark', 'transfer-pages-busy'),
    @('transfer-lifecycle', 'Light', 'transfer-hide'), @('transfer-lifecycle', 'Dark', 'transfer-hide'),
    @('transfer-lifecycle', 'Light', 'transfer-dispose'), @('transfer-lifecycle', 'Dark', 'transfer-dispose'),
    @('transfer-lifecycle', 'Light', 'transfer-dispose-drain'), @('transfer-lifecycle', 'Dark', 'transfer-dispose-drain'),
    @('transfer-lifecycle', 'Light', 'transfer-restart'), @('transfer-lifecycle', 'Dark', 'transfer-restart'),
    @('container-registry', 'Light', 'registry-initial'),
    @('container-registry', 'Light', 'registry-unavailable'),
    @('container-registry', 'Light', 'registry-loading'),
    @('container-registry', 'Light', 'registry-error'),
    @('container-registry', 'Light', 'registry-empty'),
    @('container-registry', 'Light', 'registry-content'),
    @('container-registry', 'Light', 'registry-tags-loading'),
    @('container-registry', 'Light', 'registry-tags-error'),
    @('container-registry', 'Light', 'registry-tags-empty'),
    @('container-registry', 'Light', 'registry-filtered'),
    @('container-registry', 'Light', 'registry-select'),
    @('container-registry', 'Light', 'registry-switch'),
    @('container-registry', 'Dark', 'registry-content'), @('container-registry', 'Dark', 'registry-filtered'),
    @('container-network-delete', 'Light', 'netdelete-readonly'),
    @('container-network-delete', 'Light', 'netdelete-loading'),
    @('container-network-delete', 'Light', 'netdelete-error'),
    @('container-network-delete', 'Light', 'netdelete-empty'),
    @('container-network-delete', 'Light', 'netdelete-confirm'),
    @('container-network-delete', 'Light', 'netdelete-change'),
    @('container-network-delete', 'Light', 'netdelete-success'),
    @('container-network-delete', 'Light', 'netdelete-partial'),
    @('container-network-delete', 'Light', 'netdelete-unknown'),
    @('container-network-delete', 'Light', 'netdelete-rejected'),
    @('container-network-delete', 'Light', 'netdelete-pending'),
    @('container-network-delete', 'Light', 'netdelete-recovered'),
    @('container-network-delete', 'Light', 'netdelete-close-busy'),
    @('container-network-delete', 'Dark', 'netdelete-confirm'), @('container-network-delete', 'Dark', 'netdelete-partial'), @('container-network-delete', 'Dark', 'netdelete-unknown'),
    @('container-network-create', 'Light', 'netcreate-readonly'),
    @('container-network-create', 'Light', 'netcreate-loading'),
    @('container-network-create', 'Light', 'netcreate-error'),
    @('container-network-create', 'Light', 'netcreate-auto'),
    @('container-network-create', 'Light', 'netcreate-manual'),
    @('container-network-create', 'Light', 'netcreate-ipv6'),
    @('container-network-create', 'Light', 'netcreate-masquerade'),
    @('container-network-create', 'Light', 'netcreate-invalid-name'),
    @('container-network-create', 'Light', 'netcreate-outside'),
    @('container-network-create', 'Light', 'netcreate-late-change'),
    @('container-network-create', 'Light', 'netcreate-unknown'),
    @('container-network-create', 'Light', 'netcreate-rejected'),
    @('container-network-create', 'Light', 'netcreate-pending'),
    @('container-network-create', 'Light', 'netcreate-recovered'),
    @('container-network-create', 'Light', 'netcreate-close-busy'),
    @('container-network-create', 'Light', 'netcreate-confirm'),
    @('container-network-create', 'Dark', 'netcreate-confirm'), @('container-network-create', 'Dark', 'netcreate-unknown'),
    @('container-networks', 'Light', 'network-details'),
    @('container-networks', 'Light', 'network-zero'),
    @('container-networks', 'Light', 'network-unknown'),
    @('container-networks', 'Light', 'network-legacy'),
    @('container-networks', 'Light', 'network-empty'),
    @('container-networks', 'Light', 'network-loading'),
    @('container-networks', 'Light', 'network-error'),
    @('container-networks', 'Light', 'network-unavailable'),
    @('container-networks', 'Dark', 'network-details'), @('container-networks', 'Dark', 'network-unknown'),
    @('nas-zram', 'Light', 'zram-content'),
    @('nas-zram', 'Light', 'zram-disabled'),
    @('nas-zram', 'Light', 'zram-partial'),
    @('nas-zram', 'Light', 'zram-algorithm'),
    @('nas-zram', 'Light', 'zram-empty'),
    @('nas-zram', 'Light', 'zram-loading'),
    @('nas-zram', 'Light', 'zram-error'),
    @('nas-zram', 'Light', 'zram-unavailable'),
    @('nas-zram', 'Light', 'zram-refresh'),
    @('nas-zram', 'Dark', 'zram-content'), @('nas-zram', 'Dark', 'zram-partial'),
    @('nas-external-storage', 'Light', 'extstore-content'),
    @('nas-external-storage', 'Light', 'extstore-usb'),
    @('nas-external-storage', 'Light', 'extstore-esata'),
    @('nas-external-storage', 'Light', 'extstore-filtered'),
    @('nas-external-storage', 'Light', 'extstore-partial'),
    @('nas-external-storage', 'Light', 'extstore-partial-empty'),
    @('nas-external-storage', 'Light', 'extstore-filtered-unavailable'),
    @('nas-external-storage', 'Light', 'extstore-empty'),
    @('nas-external-storage', 'Light', 'extstore-loading'),
    @('nas-external-storage', 'Light', 'extstore-error'),
    @('nas-external-storage', 'Light', 'extstore-unavailable'),
    @('nas-external-storage', 'Light', 'extstore-unknown'),
    @('nas-external-storage', 'Light', 'extstore-truncated'),
    @('nas-external-storage', 'Light', 'extstore-refresh'),
    @('nas-external-storage', 'Dark', 'extstore-content'), @('nas-external-storage', 'Dark', 'extstore-partial'),
    @('nas-power-schedule', 'Light', 'powsched-content'),
    @('nas-power-schedule', 'Light', 'powsched-enabled'),
    @('nas-power-schedule', 'Light', 'powsched-disabled'),
    @('nas-power-schedule', 'Light', 'powsched-filtered'),
    @('nas-power-schedule', 'Light', 'powsched-empty'),
    @('nas-power-schedule', 'Light', 'powsched-loading'),
    @('nas-power-schedule', 'Light', 'powsched-error'),
    @('nas-power-schedule', 'Light', 'powsched-unavailable'),
    @('nas-power-schedule', 'Light', 'powsched-partial'),
    @('nas-power-schedule', 'Light', 'powsched-unknown'),
    @('nas-power-schedule', 'Light', 'powsched-refresh'),
    @('nas-power-schedule', 'Dark', 'powsched-content'), @('nas-power-schedule', 'Dark', 'powsched-partial'),
    @('nas-remote-access', 'Light', 'remote-readonly'),
    @('nas-remote-access', 'Light', 'remote-loading'),
    @('nas-remote-access', 'Light', 'remote-error'),
    @('nas-remote-access', 'Light', 'remote-empty'),
    @('nas-remote-access', 'Light', 'remote-partial-read'),
    @('nas-remote-access', 'Light', 'remote-only-relay'),
    @('nas-remote-access', 'Light', 'remote-failed-fields'),
    @('nas-remote-access', 'Light', 'remote-relay'),
    @('nas-remote-access', 'Light', 'remote-relay-save'),
    @('nas-remote-access', 'Light', 'remote-confirm'),
    @('nas-remote-access', 'Light', 'remote-save'),
    @('nas-remote-access', 'Light', 'remote-partial'),
    @('nas-remote-access', 'Light', 'remote-unknown'),
    @('nas-remote-access', 'Light', 'remote-rejected'),
    @('nas-remote-access', 'Light', 'remote-pending'),
    @('nas-remote-access', 'Light', 'remote-recovered'),
    @('nas-remote-access', 'Light', 'remote-late-change'),
    @('nas-remote-access', 'Light', 'remote-close-busy'),
    @('nas-remote-access', 'Light', 'remote-save-read-error'),
    @('nas-remote-access', 'Dark', 'remote-confirm'), @('nas-remote-access', 'Dark', 'remote-unknown'),
    @('nas-disk-tests', 'Light', 'disk-readonly'),
    @('nas-disk-tests', 'Light', 'disk-loading'),
    @('nas-disk-tests', 'Light', 'disk-error'),
    @('nas-disk-tests', 'Light', 'disk-empty'),
    @('nas-disk-tests', 'Light', 'disk-filter'),
    @('nas-disk-tests', 'Light', 'disk-state-error'),
    @('nas-disk-tests', 'Light', 'disk-busy'),
    @('nas-disk-tests', 'Light', 'disk-busy-unknown'),
    @('nas-disk-tests', 'Light', 'disk-unsupported'),
    @('nas-disk-tests', 'Light', 'disk-history'),
    @('nas-disk-tests', 'Light', 'disk-history-error'),
    @('nas-disk-tests', 'Light', 'disk-history-empty'),
    @('nas-disk-tests', 'Light', 'disk-history-partial'),
    @('nas-disk-tests', 'Light', 'disk-quick'),
    @('nas-disk-tests', 'Light', 'disk-extended'),
    @('nas-disk-tests', 'Light', 'disk-stop'),
    @('nas-disk-tests', 'Light', 'disk-unknown'),
    @('nas-disk-tests', 'Light', 'disk-rejected'),
    @('nas-disk-tests', 'Light', 'disk-switch'),
    @('nas-disk-tests', 'Light', 'disk-late-filter'),
    @('nas-disk-tests', 'Light', 'disk-close-busy'),
    @('nas-disk-tests', 'Light', 'disk-confirm'),
    @('nas-disk-tests', 'Dark', 'disk-confirm'), @('nas-disk-tests', 'Dark', 'disk-history'),
    @('nas-task-settings', 'Light', 'task-readonly'),
    @('nas-task-settings', 'Light', 'task-detail'),
    @('nas-task-settings', 'Light', 'task-detail-error'),
    @('nas-task-settings', 'Light', 'task-loading'),
    @('nas-task-settings', 'Light', 'task-error'),
    @('nas-task-settings', 'Light', 'task-empty'),
    @('nas-task-settings', 'Light', 'task-filter'),
    @('nas-task-settings', 'Light', 'task-history'),
    @('nas-task-settings', 'Light', 'task-output'),
    @('nas-task-settings', 'Light', 'task-no-history'),
    @('nas-task-settings', 'Light', 'task-create'),
    @('nas-task-settings', 'Light', 'task-edit'),
    @('nas-task-settings', 'Light', 'task-edit-preview'),
    @('nas-task-settings', 'Light', 'task-late-edit'),
    @('nas-task-settings', 'Light', 'task-invalid'),
    @('nas-task-settings', 'Light', 'task-enable'),
    @('nas-task-settings', 'Light', 'task-disable'),
    @('nas-task-settings', 'Light', 'task-run'),
    @('nas-task-settings', 'Light', 'task-delete'),
    @('nas-task-settings', 'Light', 'task-unknown'),
    @('nas-task-settings', 'Light', 'task-rejected'),
    @('nas-task-settings', 'Dark', 'task-edit-preview'), @('nas-task-settings', 'Dark', 'task-output'),
    @('files', 'Light', ''), @('files', 'Dark', ''),
    @('selected', 'Light', ''), @('selected', 'Dark', ''),
    @('list', 'Light', ''), @('login', 'Light', ''), @('login', 'Dark', ''),
    @('login', 'Light', 'login-error'), @('login', 'Dark', 'login-error'), @('nas', 'Light', ''),
    @('files', 'Light', 'loading'), @('files', 'Light', 'empty'),
    @('filtered-empty', 'Light', ''), @('files', 'Light', 'error'),
    @('photos', 'Light', ''), @('photos', 'Dark', ''), @('chat', 'Light', ''),
    @('photos', 'Light', 'photo-error'), @('photos', 'Dark', 'photo-error'),
    @('photos', 'Light', 'photo-loading'), @('photos', 'Light', 'photo-empty'),
    @('downloads', 'Light', ''), @('downloads', 'Light', 'link-create'), @('downloads', 'Dark', 'link-create'),
    @('containers', 'Light', ''), @('vms', 'Light', ''),
    @('chat', 'Dark', ''), @('chat', 'Light', 'chat-realtime'), @('chat', 'Dark', 'chat-realtime'),
    @('downloads', 'Dark', ''), @('containers', 'Dark', ''), @('vms', 'Dark', '')
    @('chat-tools', 'Light', 'reminders'), @('chat-tools', 'Dark', 'reminders'),
    @('chat-tools', 'Light', 'schedules'), @('chat-tools', 'Dark', 'schedules'),
    @('chat-tools', 'Light', 'polls'), @('chat-tools', 'Dark', 'polls'),
    @('chat-tools', 'Light', 'advanced-loading'), @('chat-tools', 'Light', 'advanced-empty'),
    @('chat-tools', 'Light', 'advanced-error'), @('chat-tools', 'Light', 'advanced-filtered'),
    @('chat-tools', 'Light', 'advanced-readonly'), @('chat-tools', 'Light', 'advanced-review'),
    @('chat-tools', 'Light', 'advanced-success'), @('chat-tools', 'Light', 'advanced-rejected'),
    @('chat-tools', 'Light', 'actions-forward'), @('chat-tools', 'Dark', 'actions-forward'),
    @('chat-tools', 'Light', 'actions-pins'), @('chat-tools', 'Dark', 'actions-pins'),
    @('chat-tools', 'Light', 'actions-close'), @('chat-tools', 'Dark', 'actions-close'),
    @('chat-tools', 'Light', 'batch-forward'), @('chat-tools', 'Dark', 'batch-forward'),
    @('chat-tools', 'Light', 'batch-close'), @('chat-tools', 'Dark', 'batch-close'),
    @('chat-tools', 'Light', 'batch-direct'), @('chat-tools', 'Dark', 'batch-direct'),
    @('chat-tools', 'Light', 'batch-review'), @('chat-tools', 'Dark', 'batch-review'),
    @('chat-tools', 'Light', 'batch-delete'), @('chat-tools', 'Dark', 'batch-delete'),
    @('download-settings', 'Light', 'settings-basic'), @('download-settings', 'Dark', 'settings-basic'),
    @('download-settings', 'Light', 'settings-save'), @('download-settings', 'Dark', 'settings-save'),
    @('download-settings', 'Light', 'settings-review'), @('download-settings', 'Dark', 'settings-review'),
    @('download-settings', 'Light', 'settings-partial'), @('download-settings', 'Dark', 'settings-partial'),
    @('download-settings', 'Light', 'settings-loading'), @('download-settings', 'Light', 'settings-error'),
    @('download-settings', 'Light', 'settings-no-schedule'), @('download-settings', 'Light', 'settings-v1'),
    @('download-settings', 'Light', 'settings-folders'), @('download-settings', 'Dark', 'settings-folders'),
    @('download-settings', 'Light', 'settings-empty-folders'),
    @('download-batch', 'Light', 'batch-pause'), @('download-batch', 'Dark', 'batch-pause'),
    @('download-batch', 'Light', 'batch-resume'), @('download-batch', 'Dark', 'batch-resume'),
    @('download-batch', 'Light', 'batch-remove'), @('download-batch', 'Dark', 'batch-remove'),
    @('download-batch', 'Light', 'batch-finish'), @('download-batch', 'Dark', 'batch-finish'),
    @('download-batch', 'Light', 'batch-review'), @('download-batch', 'Dark', 'batch-review'),
    @('download-batch', 'Light', 'batch-partial'), @('download-batch', 'Light', 'batch-empty'),
    @('download-batch', 'Light', 'batch-filtered'), @('download-batch', 'Light', 'batch-loading'),
    @('download-batch', 'Light', 'batch-error'),
    @('download-file-options', 'Light', 'file-options'), @('download-file-options', 'Dark', 'file-options'),
    @('download-file-options', 'Light', 'file-folders'), @('download-file-options', 'Dark', 'file-folders'),
    @('download-file-options', 'Light', 'file-submit'), @('download-file-options', 'Dark', 'file-submit'),
    @('download-file-options', 'Light', 'file-empty'), @('download-file-options', 'Light', 'file-legacy'),
    @('nas-service-settings', 'Light', 'terminal'), @('nas-service-settings', 'Dark', 'terminal'),
    @('nas-service-settings', 'Light', 'proxy'), @('nas-service-settings', 'Dark', 'proxy'),
    @('nas-service-settings', 'Light', 'terminal-readonly'), @('nas-service-settings', 'Dark', 'proxy-readonly'),
    @('nas-service-settings', 'Light', 'terminal-no-port'), @('nas-service-settings', 'Light', 'terminal-loading'),
    @('nas-service-settings', 'Light', 'proxy-error'), @('nas-service-settings', 'Dark', 'proxy-error'),
    @('nas-service-settings', 'Light', 'terminal-save'), @('nas-service-settings', 'Dark', 'proxy-save'),
    @('nas-service-settings', 'Light', 'terminal-review'), @('nas-service-settings', 'Dark', 'terminal-review'),
    @('nas-service-settings', 'Light', 'proxy-invalid'), @('nas-service-settings', 'Dark', 'proxy-invalid'),
    @('nas-service-settings', 'Light', 'terminal-pending'), @('nas-service-settings', 'Dark', 'terminal-pending'),
    @('nas-service-settings', 'Light', 'terminal-recovered'), @('nas-service-settings', 'Dark', 'terminal-recovered'),
    @('nas-service-settings', 'Light', 'file-services'), @('nas-service-settings', 'Dark', 'file-services'),
    @('nas-service-settings', 'Light', 'file-partial'), @('nas-service-settings', 'Dark', 'file-partial'),
    @('nas-service-settings', 'Light', 'file-error'), @('nas-service-settings', 'Dark', 'file-error'),
    @('nas-service-settings', 'Light', 'file-unavailable'), @('nas-service-settings', 'Light', 'file-empty'),
    @('nas-service-settings', 'Light', 'file-loading'), @('nas-service-settings', 'Dark', 'file-recovered'),
    @('nas-service-settings', 'Light', 'file-save'), @('nas-service-settings', 'Dark', 'file-save'),
    @('nas-service-settings', 'Light', 'file-save-review'), @('nas-service-settings', 'Dark', 'file-save-partial'),
    @('nas-service-settings', 'Light', 'file-invalid'), @('nas-service-settings', 'Dark', 'file-pending'),
    @('nas-region-settings', 'Light', 'region-network'), @('nas-region-settings', 'Dark', 'region-network'),
    @('nas-region-settings', 'Light', 'region-manual'), @('nas-region-settings', 'Light', 'region-no-clock'),
    @('nas-region-settings', 'Light', 'region-error'), @('nas-region-settings', 'Dark', 'region-unavailable'),
    @('nas-region-settings', 'Light', 'region-loading'), @('nas-region-settings', 'Light', 'region-unknown'),
    @('nas-region-settings', 'Light', 'region-save'), @('nas-region-settings', 'Dark', 'region-save'),
    @('nas-region-settings', 'Light', 'region-save-sync'), @('nas-region-settings', 'Dark', 'region-save-sync-failed'),
    @('nas-region-settings', 'Light', 'region-save-unverified'), @('nas-region-settings', 'Light', 'region-invalid'),
    @('nas-region-settings', 'Light', 'region-manual-edit'), @('nas-region-settings', 'Dark', 'region-manual-edit'),
    @('nas-network-settings', 'Light', 'network-content'), @('nas-network-settings', 'Dark', 'network-content'),
    @('nas-network-settings', 'Light', 'network-empty'), @('nas-network-settings', 'Light', 'network-loading'),
    @('nas-network-settings', 'Light', 'network-error'), @('nas-network-settings', 'Dark', 'network-unavailable'),
    @('nas-network-settings', 'Light', 'network-partial'), @('nas-network-settings', 'Dark', 'network-unknown'),
    @('nas-network-settings', 'Light', 'network-recovered'),
    @('nas-network-settings', 'Light', 'network-save'), @('nas-network-settings', 'Dark', 'network-save'),
    @('nas-network-settings', 'Light', 'network-save-unknown'), @('nas-network-settings', 'Light', 'network-invalid'),
    @('nas-network-settings', 'Light', 'network-edit-unknown'), @('nas-network-settings', 'Dark', 'network-reconnect'),
    @('nas-network-settings', 'Light', 'network-fresh-login'),
    @('nas-security-settings', 'Light', 'security-content'), @('nas-security-settings', 'Dark', 'security-content'),
    @('nas-security-settings', 'Light', 'security-partial'), @('nas-security-settings', 'Dark', 'security-recovered'),
    @('nas-security-settings', 'Light', 'security-loading'), @('nas-security-settings', 'Light', 'security-empty'),
    @('nas-security-settings', 'Light', 'security-error'), @('nas-security-settings', 'Dark', 'security-unavailable'),
    @('nas-security-settings', 'Light', 'security-no-expiry'),
    @('nas-security-settings', 'Light', 'security-save'), @('nas-security-settings', 'Dark', 'security-save'),
    @('nas-security-settings', 'Light', 'security-save-partial'), @('nas-security-settings', 'Dark', 'security-save-unknown'),
    @('nas-security-settings', 'Light', 'security-invalid'), @('nas-security-settings', 'Dark', 'security-missing-profile'),
    @('nas-security-settings', 'Light', 'security-pending'),
    @('nas-hardware-settings', 'Light', 'hardware-content'), @('nas-hardware-settings', 'Dark', 'hardware-content'),
    @('nas-hardware-settings', 'Light', 'hardware-loading'), @('nas-hardware-settings', 'Light', 'hardware-empty'),
    @('nas-hardware-settings', 'Light', 'hardware-error'), @('nas-hardware-settings', 'Dark', 'hardware-unavailable'),
    @('nas-hardware-settings', 'Light', 'hardware-partial'), @('nas-hardware-settings', 'Dark', 'hardware-recovered'),
    @('nas-hardware-settings', 'Light', 'hardware-ups-empty'),
    @('nas-hardware-settings', 'Light', 'hardware-save'), @('nas-hardware-settings', 'Dark', 'hardware-save'),
    @('nas-hardware-settings', 'Light', 'hardware-save-partial'), @('nas-hardware-settings', 'Dark', 'hardware-save-unknown'),
    @('nas-hardware-settings', 'Light', 'hardware-invalid'), @('nas-hardware-settings', 'Dark', 'hardware-pending'),
    @('nas-hardware-settings', 'Light', 'hardware-ups-edit'),
    @('nas-ddns-settings', 'Light', 'ddns-content'), @('nas-ddns-settings', 'Dark', 'ddns-content'),
    @('nas-ddns-settings', 'Light', 'ddns-empty'), @('nas-ddns-settings', 'Light', 'ddns-loading'),
    @('nas-ddns-settings', 'Light', 'ddns-error'), @('nas-ddns-settings', 'Dark', 'ddns-unavailable'),
    @('nas-ddns-settings', 'Light', 'ddns-no-address'),
    @('nas-ddns-settings', 'Light', 'ddns-create'), @('nas-ddns-settings', 'Dark', 'ddns-save'),
    @('nas-ddns-settings', 'Light', 'ddns-test'), @('nas-ddns-settings', 'Light', 'ddns-delete'),
    @('nas-ddns-settings', 'Dark', 'ddns-update'), @('nas-ddns-settings', 'Dark', 'ddns-unknown'),
    @('nas-ddns-settings', 'Light', 'ddns-rejected'), @('nas-ddns-settings', 'Light', 'ddns-invalid'),
    @('nas-ddns-settings', 'Light', 'ddns-late-change'), @('nas-ddns-settings', 'Light', 'ddns-pending'),
    @('nas-package-settings', 'Light', 'pkg-content'), @('nas-package-settings', 'Dark', 'pkg-content'),
    @('nas-package-settings', 'Light', 'pkg-empty'), @('nas-package-settings', 'Light', 'pkg-loading'),
    @('nas-package-settings', 'Light', 'pkg-error'), @('nas-package-settings', 'Light', 'pkg-filter'),
    @('nas-package-settings', 'Light', 'pkg-start'), @('nas-package-settings', 'Dark', 'pkg-stop'),
    @('nas-package-settings', 'Light', 'pkg-uninstall'), @('nas-package-settings', 'Dark', 'pkg-unknown'),
    @('nas-package-settings', 'Light', 'pkg-rejected'), @('nas-package-settings', 'Light', 'pkg-conflict'),
    @('nas-package-settings', 'Light', 'pkg-pending'), @('nas-package-settings', 'Dark', 'pkg-recovered'),
    @('nas-package-settings', 'Light', 'pkg-changed-target'), @('nas-package-settings', 'Light', 'pkg-control-only'),
    @('nas-package-settings', 'Light', 'pkg-missing-permission'), @('nas-package-settings', 'Light', 'pkg-close-busy'),
    @('nas-package-settings', 'Light', 'pkg-search-change'),
    @('nas-directory-settings', 'Light', 'dir-content'), @('nas-directory-settings', 'Dark', 'dir-group-content'),
    @('nas-directory-settings', 'Light', 'dir-empty'), @('nas-directory-settings', 'Light', 'dir-loading'),
    @('nas-directory-settings', 'Light', 'dir-user-error'), @('nas-directory-settings', 'Light', 'dir-group-error'),
    @('nas-directory-settings', 'Light', 'dir-create-user'), @('nas-directory-settings', 'Dark', 'dir-create-group'),
    @('nas-directory-settings', 'Dark', 'dir-edit-user'), @('nas-directory-settings', 'Light', 'dir-edit-group'),
    @('nas-directory-settings', 'Light', 'dir-delete-user'), @('nas-directory-settings', 'Light', 'dir-delete-group'),
    @('nas-directory-settings', 'Light', 'dir-membership'), @('nas-directory-settings', 'Light', 'dir-current'),
    @('nas-directory-settings', 'Light', 'dir-missing-fields'), @('nas-directory-settings', 'Dark', 'dir-unknown'),
    @('nas-directory-settings', 'Light', 'dir-rejected'), @('nas-directory-settings', 'Light', 'dir-conflict'),
    @('nas-directory-settings', 'Light', 'dir-mismatch'), @('nas-directory-settings', 'Light', 'dir-late-password'),
    @('nas-directory-settings', 'Light', 'dir-filter'), @('nas-directory-settings', 'Light', 'dir-pending'),
    @('nas-directory-settings', 'Light', 'dir-recovered'), @('nas-directory-settings', 'Light', 'dir-close-busy'),
    @('nas-directory-settings', 'Light', 'dir-switch-secret'),
    @('nas-power-settings', 'Light', 'power-readonly'), @('nas-power-settings', 'Light', 'power-loading'),
    @('nas-power-settings', 'Light', 'power-load-error'), @('nas-power-settings', 'Light', 'power-shutdown'),
    @('nas-power-settings', 'Dark', 'power-reboot'), @('nas-power-settings', 'Dark', 'power-unknown'),
    @('nas-power-settings', 'Light', 'power-rejected'), @('nas-power-settings', 'Light', 'power-pending'),
    @('nas-power-settings', 'Light', 'power-fresh'), @('nas-power-settings', 'Light', 'power-switch-action'),
    @('nas-power-settings', 'Light', 'power-close-busy'),
    @('nas-connection-settings', 'Light', 'conn-readonly'), @('nas-connection-settings', 'Dark', 'conn-readonly'),
    @('nas-connection-settings', 'Light', 'conn-empty'), @('nas-connection-settings', 'Light', 'conn-loading'),
    @('nas-connection-settings', 'Light', 'conn-error'), @('nas-connection-settings', 'Light', 'conn-partial'),
    @('nas-connection-settings', 'Light', 'conn-missing'), @('nas-connection-settings', 'Light', 'conn-ambiguous'),
    @('nas-connection-settings', 'Light', 'conn-web'), @('nas-connection-settings', 'Dark', 'conn-service'),
    @('nas-connection-settings', 'Light', 'conn-current'), @('nas-connection-settings', 'Light', 'conn-current-reversed'),
    @('nas-connection-settings', 'Light', 'conn-unknown-current'), @('nas-connection-settings', 'Dark', 'conn-unknown'),
    @('nas-connection-settings', 'Light', 'conn-rejected'), @('nas-connection-settings', 'Light', 'conn-conflict'),
    @('nas-connection-settings', 'Light', 'conn-pending'), @('nas-connection-settings', 'Light', 'conn-recovered'),
    @('nas-connection-settings', 'Light', 'conn-search'), @('nas-connection-settings', 'Light', 'conn-switch-target'),
    @('nas-connection-settings', 'Light', 'conn-late-search'), @('nas-connection-settings', 'Light', 'conn-close-busy')
)
$savedEnvironment = @{}
$runResults = [Collections.Generic.List[object]]::new()
$reportPath = Join-Path $review 'results.json'
foreach ($key in @('LANSTASH_SMOKE_SCENARIO', 'LANSTASH_SMOKE_THEME', 'LANSTASH_SMOKE_STATE', 'LANSTASH_SMOKE_WIDTH', 'LANSTASH_SMOKE_HEIGHT', 'LANSTASH_SMOKE_PANE', 'LANSTASH_SMOKE_LANGUAGE')) {
    $savedEnvironment[$key] = [Environment]::GetEnvironmentVariable($key, 'Process')
}
try {
    $env:LANSTASH_SMOKE_WIDTH = "$WindowWidth"
    $env:LANSTASH_SMOKE_HEIGHT = "$WindowHeight"
    $env:LANSTASH_SMOKE_PANE = $PaneState
    $env:LANSTASH_SMOKE_LANGUAGE = $Language
    foreach ($case in $cases) {
        if ($Scenarios.Count -gt 0 -and $case[0] -notin $Scenarios) { continue }
        if ($States.Count -gt 0 -and $case[2] -notin $States) { continue }
        $env:LANSTASH_SMOKE_SCENARIO = $case[0]
        $env:LANSTASH_SMOKE_THEME = $case[1]
        $env:LANSTASH_SMOKE_STATE = $case[2]
        $started = Get-Date
        $process = Start-Process -FilePath (Join-Path $output 'LanStash.App.exe') -WindowStyle Hidden -PassThru
        try {
            $timer = [Diagnostics.Stopwatch]::StartNew()
            do {
                if ($process.WaitForExit(250)) { throw "合成宿主提前退出：$case" }
                $snapshot = Get-Item -LiteralPath (Join-Path $output 'workspace-smoke.png') -ErrorAction SilentlyContinue
                $complete = Get-Item -LiteralPath (Join-Path $output 'smoke-complete.txt') -ErrorAction SilentlyContinue
            } while (($null -eq $complete -or $complete.LastWriteTime -lt $started) -and $timer.Elapsed.TotalSeconds -lt 30)
            if ($null -eq $snapshot) { throw "没有生成截图：$case" }
            if ($null -eq $complete -or $complete.LastWriteTime -lt $started -or $snapshot.Length -lt 100) { throw "截图尚未完整写入：$case" }
            if ($snapshot.LastWriteTime -lt $started) { throw "没有通过状态断言的新截图：$case" }
            $label = if ($case[2]) { $case[2] } else { $case[0] }
            if ($Scenarios.Count -ne 1) { $label = $case[0] + '-' + $label }
            $name = "$label-$($case[1].ToLowerInvariant()).png"
        Copy-Item -LiteralPath $snapshot.FullName -Destination (Join-Path $review $name)
        if ($case[0] -eq 'vm-console') {
            $consolePreview = Get-Item -LiteralPath (Join-Path $output 'workspace-console-page.png') -ErrorAction SilentlyContinue
            if ($null -ne $consolePreview -and $consolePreview.LastWriteTime -ge $started) {
                Copy-Item -LiteralPath $consolePreview.FullName -Destination (Join-Path $review ($label + '-page-' + $case[1].ToLowerInvariant() + '.png'))
            }
        }
            Write-Output ("PASS {0} ({1:N1}s)" -f $name, $timer.Elapsed.TotalSeconds)
            $runResults.Add(@{ scenario=$case[0]; theme=$case[1]; state=$case[2]; status='passed'; seconds=$timer.Elapsed.TotalSeconds; artifact=$name })
        }
        catch {
            $failure = $_.Exception.Message
            $runResults.Add(@{ scenario=$case[0]; theme=$case[1]; state=$case[2]; status='failed'; seconds=$timer.Elapsed.TotalSeconds; error=$failure })
            if (-not $ContinueOnFailure) { throw }
            Write-Warning ("FAIL {0}/{1}/{2}: {3}" -f $case[0], $case[1], $case[2], $failure)
        }
        finally {
            if (-not $process.HasExited) { $process.Kill(); $process.WaitForExit() }
            $process.Dispose()
            # 正式回归产物，不含设备数据；即使中途停止，也保留已完成场景的真实状态。
            @{ schemaVersion=1; language=$Language; width=$WindowWidth; height=$WindowHeight; results=$runResults.ToArray() } |
                ConvertTo-Json -Depth 5 | Set-Content -LiteralPath $reportPath -Encoding utf8
        }
    }
}
finally {
    foreach ($key in $savedEnvironment.Keys) {
        [Environment]::SetEnvironmentVariable($key, $savedEnvironment[$key], 'Process')
    }
}
if ($runResults.Count -eq 0) { throw '没有匹配的原生回归场景。' }
$failedCount = @($runResults | Where-Object { $_.status -eq 'failed' }).Count
Write-Output "原生界面合成回归完成：$review；总数 $($runResults.Count)，失败 $failedCount"
if ($failedCount -gt 0) { throw "原生回归存在 $failedCount 项失败，详见 results.json。" }
